8 == 8 //true
8 != 8 //false
8 === 8 //true
8 !== 8 //false
8 == '8' //true
8 === '8' //false
8 != '8' //false
8 !== '8' //true
8 === +'8' //true
8 === Number('8') //true
NaN === NaN //false
null === null //true
undefined === undefined //true
